/// Flutter icons NanoIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NanoIcons
///      fonts:
///       - asset: fonts/NanoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NanoIcons {
  NanoIcons._();

  static const _kFontFam = 'NanoIcons';
  static const String _kFontPkg = null;

  static const IconData solar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analytics = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData earth_pictures = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trees = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electricity_tower = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
